### PR TITLE
This can fix your Android compile error

### PR DESCRIPTION
**Pull request by Heropowerbrine**
Don't mind me, I saw you had that android v7 Tools obj error thing on your compile

### CODE REVIEW

**Comment by tposejank** [comment]
Lets see

**Comment by tposejank** [comment]
image
Still get this issue, I can't figure out what it's due to

**Comment by tposejank** [comment]
Do you mayhaps know why the Android SDK my workflows are using are 28 and not 29+?

**Comment by Heropowerbrine** [comment]
Oh, if I'm not wrong back then we were using 28 because the external and media storage directories were causing issues on Android 11 and higher for some reason
But this should have been fixed already so I don't think it matters anymore lol

**Comment by tposejank** [comment]
I removed the line that sets the android SDK version to 28. That fixed it

**Pull request merged**
